AY2223S2-CS2113-T12-3/tp

src/main/java/seedu/duke/Duke.java
src/main/java/seedu/duke/Parser.java
src/main/java/seedu/duke/Storage.java
src/test/java/seedu/duke/ParserTest.java
src/test/java/seedu/duke/StorageTest.java

Added delete functionality in parser class. It handles the user's list of saved modules in the database by calling a separate function in Storage class. Added JUnit test for the delete feature and it passed the test case.

Added Parser class, delete functionality and JUnit tests.

---

src/main/java/seedu/duke/Module.java
src/main/java/seedu/duke/Parser.java
src/main/java/seedu/duke/University.java

Add a Parser class containing parseCommand(userInput), printPUModules(univID), printPUList() and printCurrentModList() methods.
1. The parseCommand(userInput) method to read the command and execute the command accordingly.
2. The printPUModules(univID) method to print out the list of modules under the targetted PU.
3. The printPUList() method to print out the list of PUs.
4. The printCurrentModList() to print out the list of modules that the user has added to his list of interests.
Add getter methods for attributes in both Module and University classes.

Add Parser class and Add getter methods in Module and University classes

---

src/main/java/seedu/duke/UI.java
src/main/resources/META-INF/MANIFEST.MF

Added case to remove current saved modules and calls respective functions.

Added support in UI function for delete functionality

---

data/saved_modules.txt
src/main/java/seedu/duke/Duke.java
src/main/java/seedu/duke/Parser.java
src/main/java/seedu/duke/UI.java

Changed Code in UI and Parder classes such that Printing out lines to users are only done in the UI class, whileas Parser class takes care of the execution of commands.

Refactored Code in UI and Parser Classes

---

src/main/java/seedu/duke/Duke.java
src/main/java/seedu/duke/Parser.java
src/main/java/seedu/duke/Storage.java
src/main/java/seedu/duke/UI.java
src/main/java/seedu/duke/command/AddModuleCommand.java
src/main/java/seedu/duke/command/Command.java
src/main/java/seedu/duke/command/DeleteModuleCommand.java
src/main/java/seedu/duke/command/ExitCommand.java
src/main/java/seedu/duke/command/InvalidCommand.java
src/main/java/seedu/duke/command/ListCurrentCommand.java
src/main/java/seedu/duke/command/ListPuCommand.java
src/main/java/seedu/duke/command/ListPuModulesCommand.java
src/test/java/seedu/duke/command/AddModuleCommandTest.java

1. Added whole new Command Class
2. Changed Parser handleUserCommand to return Command instead
3. Duke runs Command.execute after getting the command from handleUserCommand function
4. Added JUnit for addModuleCommand testing

Add command class to allow Parser to return commands to be executed

---

data/saved_modules.txt
src/main/java/seedu/duke/Parser.java
src/main/java/seedu/duke/UI.java
src/main/java/seedu/duke/command/DeleteModuleCommand.java
src/main/java/seedu/duke/command/HelpCommand.java
src/test/java/seedu/duke/ParserTest.java
text-ui-test/EXPECTED.TXT

Added a help function that provides a list of commands and its respective format.

Added help function

---

src/main/java/seedu/duke/Duke.java
src/main/java/seedu/duke/Parser.java
src/main/java/seedu/duke/Storage.java
src/main/java/seedu/duke/UI.java
src/main/java/seedu/duke/command/DeleteModuleCommand.java
src/test/java/seedu/duke/ParserTest.java
src/test/java/seedu/duke/StorageTest.java
src/test/java/seedu/duke/command/AddModuleCommandTest.java

Fixed some bugs and added stringToInt function to catch exceptions. Moved deletemodule function from Parser to Storage.

Fixed bugs and relocated deletemodule function

---

src/main/java/seedu/duke/Parser.java
src/main/java/seedu/duke/UI.java
src/main/java/seedu/duke/command/ExceptionHandleCommand.java
src/main/java/seedu/duke/exceptions/InvalidCommandException.java
src/main/java/seedu/duke/exceptions/InvalidModuleException.java
src/main/java/seedu/duke/exceptions/InvalidPuException.java

Created Exceptions class with the following classes which extends from it:
* InvalidCommandException
* InvalidModuleException
* InvalidPuException
For ListPu and Add functions, this commit includes the respective exceptions by throwing in the respective "handle" functions and catching them in Parser class under the "prepare" functions. They will also print the respective messages.

Create Exceptions class and add exceptions in Parser class

---

src/main/java/seedu/duke/Duke.java
src/main/java/seedu/duke/Parser.java
src/main/java/seedu/duke/UI.java
src/main/java/seedu/duke/command/ExceptionHandleCommand.java
src/main/java/seedu/duke/command/InvalidCommand.java
src/main/java/seedu/duke/command/ListCurrentCommand.java
text-ui-test/EXPECTED.TXT

- Change parseUserCommand to allow the userCommandFirstKeyword input to be case insensitive.
- Add an exception to catch invalid command input for the list.
- Change both the prepareListPuModulesCommand() and handleListPuModulesCommand() so that the user can input list [Index] or list [Uni Abbrevations] to list out the PU modules.
- Made some minor changes to UI print functions to make them look more coherent.

Enhance function in Parser and UI

---

data/saved_modules.txt
src/test/java/seedu/duke/UITest.java
src/test/java/seedu/duke/command/ListCurrentCommandTest.java
src/test/java/seedu/duke/command/ListPuCommandTest.java
src/test/java/seedu/duke/command/ListPuModulesCommandTest.java

**Describe your proposed enhancement.**
Adding JUnit5 testing for UI class and Command List functions
UI class JUnit5 Testing will test the print functions and it's output.
Command List Functions uses the print functions by UI class, thus it will be added later
**Why should this enhancement be added? Explain its benefits/significance.**
Prevent any printing errors due to developer mistakenly inputting an incorrect string that would affect the output of our program

[Enchacement] Added JUnit5 Testing for UI class, ListCommands

---

.gitignore
src/main/java/seedu/duke/Deadline.java
src/main/java/seedu/duke/Duke.java
src/main/java/seedu/duke/Parser.java
src/main/java/seedu/duke/Storage.java
src/main/java/seedu/duke/UI.java
src/main/java/seedu/duke/command/AddDeadlineCommand.java
src/main/java/seedu/duke/command/AddModuleCommand.java
src/main/java/seedu/duke/command/DeleteDeadlineCommand.java
src/main/java/seedu/duke/command/ListDeadlinesCommand.java
src/test/java/seedu/duke/command/DeleteModuleCommandTest.java
src/test/java/seedu/duke/command/ExitCommandTest.java
src/test/java/seedu/duke/command/HelpCommandTest.java
src/test/java/seedu/duke/command/InvalidCommandTest.java

Add new feature -- Deadlines and its respective commands:
* `/deadline/list` This will list the current deadlines added by user
* `/deadline/add` This adds a deadline that is given by the user in the format: `/deadline/add [TASK] /by [DUE DATE]`
* ** Note due date has a format dd-MM-yyyy
* `/deadline/remove` This removes a deadline by 1-based index: `/deadline/remove 1`
Add a reminder feature. The function is in Storage. So anything that is 7 days or less will be printed together with Greeting/Welcome message. The code takes in user's System Time.

Add deadlines functionality and reminder functionality

---

data/saved_modules.txt
src/main/java/seedu/duke/Parser.java
src/main/java/seedu/duke/UI.java
src/main/java/seedu/duke/command/ListCurrentPuCommand.java
src/test/java/seedu/duke/UITest.java
src/test/java/seedu/duke/command/ListCurrentPuCommandTest.java

Added list current pu command that allows user to list modules from specific a PU that they have added to their list

Add seperate list function

---

data/saved_modules.txt
src/main/java/seedu/duke/Parser.java
src/main/java/seedu/duke/UI.java
src/main/java/seedu/duke/command/ListCurrentPuCommand.java
src/test/java/seedu/duke/UITest.java
src/test/java/seedu/duke/command/HelpCommandTest.java
src/test/java/seedu/duke/command/ListCurrentPuCommandTest.java

Added ListCurrentPuCommand
Added Junit5 testing for it

Add seperate list function v2

---

src/main/java/seedu/duke/Parser.java

**Issues #49**
- Debugged the bug where the program crashes when input "list [index]" is out of bounds of the universities arraylist
**Issues #61**
- Debugged the bug where the program crashes when "list " with an empty whitespace is inputted
**Issues #65**
- Extracted the commands in the list switch case and put them into prepareListCommands function to make the parseUserCommand function more OOP

Complete Issues #49, #61 ,and #65

---

src/main/java/seedu/duke/UI.java
src/test/java/seedu/duke/UITest.java
src/test/java/seedu/duke/command/HelpCommandTest.java

and it's respective tests to include the program's latest features

[Enhancement] Update /help command 

---

src/main/java/seedu/duke/DeadlineStorage.java
src/main/java/seedu/duke/Duke.java
src/main/java/seedu/duke/Parser.java
src/main/java/seedu/duke/Storage.java
src/main/java/seedu/duke/UI.java
src/main/java/seedu/duke/command/AddDeadlineCommand.java
src/main/java/seedu/duke/command/DeleteDeadlineCommand.java
src/test/java/seedu/duke/command/DeleteModuleCommandTest.java
src/test/java/seedu/duke/command/ExitCommandTest.java
src/test/java/seedu/duke/command/HelpCommandTest.java
src/test/java/seedu/duke/command/InvalidCommandTest.java

Moved deadline storage related code from Storage class to new DeadlineStorage class. Fix bugs 94, 117, 119, 122, 144.

Fix bug and refactor code to DeadlineStorage

---

docs/UserGuide.md
src/main/java/seedu/duke/DataReader.java
src/main/java/seedu/duke/Module.java
src/main/java/seedu/duke/Storage.java
src/main/java/seedu/duke/UI.java
src/main/java/seedu/duke/command/ListPuModulesCommand.java
src/test/java/seedu/duke/UITest.java
src/test/java/seedu/duke/command/ListCurrentCommandTest.java
src/test/java/seedu/duke/command/ListCurrentPuCommandTest.java
src/test/java/seedu/duke/command/ListPuCommandTest.java
src/test/java/seedu/duke/command/ListPuModulesCommandTest.java

Changed ArrayList modules in both storage and datareader to sort according to how long their print statements would be with all the module information
Changed list functions to be more readability and user friendly

Change printing functions sort

---

src/main/java/seedu/duke/Duke.java
src/main/java/seedu/duke/budget/BudgetPlanner.java
src/main/java/seedu/duke/budget/BudgetStorage.java
src/test/java/seedu/duke/ParserTest.java
src/test/java/seedu/duke/budget/BudgetPlannerTest.java
src/test/java/seedu/duke/budget/BudgetStorageTest.java
src/test/java/seedu/duke/command/DeleteModuleCommandTest.java
src/test/java/seedu/duke/command/ExitCommandTest.java
src/test/java/seedu/duke/command/HelpCommandTest.java
src/test/java/seedu/duke/command/InvalidCommandTest.java

Update the instantiation of BudgetPlanner class and BudgetStorage class in related classes and tests.
Add a "@BeforeEach" for BudgetPlanner Test and BudgetStorageTest to reset values in BudgetPlanner.

Change BudgetPlanner and BudgetStorage into singleton pattern

---

src/main/java/seedu/duke/Duke.java
src/main/java/seedu/duke/Parser.java
src/test/java/seedu/duke/ParserTest.java
src/test/java/seedu/duke/command/DeleteModuleCommandTest.java
src/test/java/seedu/duke/command/ExitCommandTest.java
src/test/java/seedu/duke/command/HelpCommandTest.java
src/test/java/seedu/duke/command/InvalidCommandTest.java

Update the instantiation of Parser class in related classes and tests

Change Parser class into singleton pattern

---

src/main/java/seedu/duke/Parser.java
src/main/java/seedu/duke/UI.java
src/test/java/seedu/duke/StorageTest.java
src/test/java/seedu/duke/UITest.java
src/test/java/seedu/duke/command/HelpCommandTest.java

Changed add function to use index relative to specific PU module list instead of module code
Updated help function according

Change add function to use index

---

docs/UserGuide.md

This issues are all occured by missing guide how to use /filter in UG. So I add the guide in UG.
closed #136
closed #124
closed #116
closed #102.

Docs: Add filter guide in UG

---

src/main/java/seedu/duke/Parser.java
src/main/java/seedu/duke/UI.java
src/main/java/seedu/duke/command/ListMappableNusModsCommand.java
src/test/java/seedu/duke/ParserTest.java

Include a ```/search /mods``` command to show the list of mappable nus mods in SEP Helper.

Enhance search command 

---

docs/UserGuide.md
src/main/java/seedu/duke/Parser.java
src/main/java/seedu/duke/UI.java
src/main/java/seedu/duke/command/ListFoundNusModsCommand.java
src/main/java/seedu/duke/command/ListMappableNusModsCommand.java

Add JavaDocs for Parser Class and its functions.
Add JavaDocs in the UI Class's functions

Update User Guides & JavaDocs

---

docs/DeveloperGuide.md

Fix link bugs in DG's content page. Fix bug in deadlinelist parser's png file.

Fix bugs in DG
